site_name: EazyFTW's Plugin Documentation

repo_name: '/EazyFTW/Docs'
repo_url: 'https://github.com/EazyFTW/Docs'

copyright: 'Copyright &copy; 2018 EazyFTW'

theme:
  name: '
  custom_dir: 'theme'
  language: 'en'

  palette:
    primary: 'light blue'
    accent: 'light blue'

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  logo: 'images/logo.png'

  feature:
    tabs: true

markdown_extensions:
  - admonition

extra:
  social:
    - type: 'github'
      link: 'https://github.com/EazyFTW'
    - type: 'twitter'
      link: 'https://twitter.com/EazyFTW_MC'
